package com.meiya.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.meiya.greendao.GreenNews;
import com.meiya.greendao.GreenDetail;
import com.meiya.greendao.GreenVideo;
import com.meiya.greendao.GreenPicflow;

import com.meiya.greendao.GreenNewsDao;
import com.meiya.greendao.GreenDetailDao;
import com.meiya.greendao.GreenVideoDao;
import com.meiya.greendao.GreenPicflowDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenNewsDaoConfig;
    private final DaoConfig greenDetailDaoConfig;
    private final DaoConfig greenVideoDaoConfig;
    private final DaoConfig greenPicflowDaoConfig;

    private final GreenNewsDao greenNewsDao;
    private final GreenDetailDao greenDetailDao;
    private final GreenVideoDao greenVideoDao;
    private final GreenPicflowDao greenPicflowDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenNewsDaoConfig = daoConfigMap.get(GreenNewsDao.class).clone();
        greenNewsDaoConfig.initIdentityScope(type);

        greenDetailDaoConfig = daoConfigMap.get(GreenDetailDao.class).clone();
        greenDetailDaoConfig.initIdentityScope(type);

        greenVideoDaoConfig = daoConfigMap.get(GreenVideoDao.class).clone();
        greenVideoDaoConfig.initIdentityScope(type);

        greenPicflowDaoConfig = daoConfigMap.get(GreenPicflowDao.class).clone();
        greenPicflowDaoConfig.initIdentityScope(type);

        greenNewsDao = new GreenNewsDao(greenNewsDaoConfig, this);
        greenDetailDao = new GreenDetailDao(greenDetailDaoConfig, this);
        greenVideoDao = new GreenVideoDao(greenVideoDaoConfig, this);
        greenPicflowDao = new GreenPicflowDao(greenPicflowDaoConfig, this);

        registerDao(GreenNews.class, greenNewsDao);
        registerDao(GreenDetail.class, greenDetailDao);
        registerDao(GreenVideo.class, greenVideoDao);
        registerDao(GreenPicflow.class, greenPicflowDao);
    }
    
    public void clear() {
        greenNewsDaoConfig.getIdentityScope().clear();
        greenDetailDaoConfig.getIdentityScope().clear();
        greenVideoDaoConfig.getIdentityScope().clear();
        greenPicflowDaoConfig.getIdentityScope().clear();
    }

    public GreenNewsDao getGreenNewsDao() {
        return greenNewsDao;
    }

    public GreenDetailDao getGreenDetailDao() {
        return greenDetailDao;
    }

    public GreenVideoDao getGreenVideoDao() {
        return greenVideoDao;
    }

    public GreenPicflowDao getGreenPicflowDao() {
        return greenPicflowDao;
    }

}
