package com.meiya.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GREEN_VIDEO".
 */
public class GreenVideo {

    private Long id;
    private String vid;
    private String videolist;

    public GreenVideo() {
    }

    public GreenVideo(Long id) {
        this.id = id;
    }

    public GreenVideo(Long id, String vid, String videolist) {
        this.id = id;
        this.vid = vid;
        this.videolist = videolist;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVid() {
        return vid;
    }

    public void setVid(String vid) {
        this.vid = vid;
    }

    public String getVideolist() {
        return videolist;
    }

    public void setVideolist(String videolist) {
        this.videolist = videolist;
    }

}
