package com.meiya.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.meiya.greendao.GreenPicflow;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_PICFLOW".
*/
public class GreenPicflowDao extends AbstractDao<GreenPicflow, Long> {

    public static final String TABLENAME = "GREEN_PICFLOW";

    /**
     * Properties of entity GreenPicflow.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Setid = new Property(1, String.class, "setid", false, "SETID");
        public final static Property Picflow = new Property(2, String.class, "picflow", false, "PICFLOW");
    };


    public GreenPicflowDao(DaoConfig config) {
        super(config);
    }
    
    public GreenPicflowDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_PICFLOW\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SETID\" TEXT," + // 1: setid
                "\"PICFLOW\" TEXT);"); // 2: picflow
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_PICFLOW\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GreenPicflow entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String setid = entity.getSetid();
        if (setid != null) {
            stmt.bindString(2, setid);
        }
 
        String picflow = entity.getPicflow();
        if (picflow != null) {
            stmt.bindString(3, picflow);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GreenPicflow readEntity(Cursor cursor, int offset) {
        GreenPicflow entity = new GreenPicflow( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // setid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // picflow
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GreenPicflow entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSetid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPicflow(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GreenPicflow entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GreenPicflow entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
