package com.meiya.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GREEN_DETAIL".
 */
public class GreenDetail {

    private Long id;
    private Integer newsId;
    private String details;

    public GreenDetail() {
    }

    public GreenDetail(Long id) {
        this.id = id;
    }

    public GreenDetail(Long id, Integer newsId, String details) {
        this.id = id;
        this.newsId = newsId;
        this.details = details;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNewsId() {
        return newsId;
    }

    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

}
